# Install Python build dependencies
- name: Install Python build dependencies
  package:
    name: >
      python-devel, libffi-devel, openssl-devel, libselinux-python,
      python-virtualenv
    state: present
  become: true

# Create a virtual environment and activate it
- name: Create a virtual environment
  command: "virtualenv {{ targetenv }}"

- name: Upgrade pip==9.0.1 to fix an issue when installing kolla-ansible
  pip:
   name:
     - pip==9.0.1
   state: present
  become: true

- name: Install pbr package
  pip:
    name: pbr
  become: true

# When install kolla-ansible==9.2.0, make sure pip==9.0.1.
# Other pip version might have an issue
- name: Install kolla_ansible to system
  pip:
    name: kolla-ansible==9.2.0
  become: true

- name: Install python packages to {{ targetenv }}
  pip:
    # Ensure the version of pip is not latest, pip install pip==9.0.1
    name: pip>=19.1.1, pbr, ansible<2.10, gitdb2==2.0.0
    virtualenv: "{{ targetenv }}"
