
# Fix issue that raised by latest docker version
- name: Find docker_version_min string in kolla_ansible repo
  shell: grep "docker_version_min:" -lr "{{ kolla_ansible_dir }}"
  register: filename
  ignore_errors: true

# Set docker_version_min to 0.0.1
- name: Replace docker_version_min with lower value
  replace:
    path: "{{ filename.stdout }}"
    regexp: "1.10.0"
    replace: "0.0.1"
  when: filename.rc == 0

- name: Confirm modification in kolla_ansible repo
  shell: grep 'docker_version_min:' -nr "{{ filename.stdout }}"
  register: result
  when: filename.rc == 0

- debug: msg="{{ result.stdout_lines }}"
  when: filename.rc == 0
