# Install the OpenStack CLI client
- name: Install OpenStack CLI client
  pip:
    name: python-openstackclient
    virtualenv: "{{ targetenv }}"

# Fix No module named queue issue
- name: Fix no module named queue issue in utils.py
  lineinfile:
    path: "{{ targetenv }}/lib/python2.7/site-packages/openstack/utils.py"
    regexp: '^import queue'
    line: 'import Queue as queue'

- name: Fix no module named queue issue in openstackcloud.py
  lineinfile:
    path: "{{ targetenv }}/lib/python2.7/site-packages/openstack/cloud/openstackcloud.py"
    regexp: '^import queue'
    line: 'import Queue as queue'

# Copy shell script generaterc.sh to remote
- name: Copy shell script generaterc.sh to remote
  copy:
    src: "{{ item }}"
    dest: "{{ local_temp }}/{{ item }}"
    mode: u+rxw,g-rwx,o-rwx
  with_items:
    - generaterc.sh

# Generate openrc file and import
- name: Generate openrc file
  shell: /bin/bash generaterc.sh > generaterc.txt
  args:
    chdir: "{{ local_temp }}"
  environment:
    OPS_VIRTUAL_PATH:  "{{ targetenv }}"
    KOLLA_ANSIBLE_PATH: "{{ kolla_ansible_dir }}"
