# Disable IPv6
- name: Disable IPv6
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: "{{ item.reload }}"
  with_items:
    - { name: net.ipv6.conf.all.disable_ipv6, value: 1, reload: no }
    - { name: net.ipv6.conf.default.disable_ipv6, value: 1, reload: yes}
  become: true

# Check firewalld
- name: Check if firewalld is installed
  command: rpm -q firewalld
  args:
    warn: false
  register: firewalld_check
  changed_when: false
  failed_when: firewalld_check.rc > 1

# Disable firewalld
- name: Stop firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: firewalld_check.rc == 0
  become: true

# Disable selinux on all the nodes
- name: Disable SELinux
  selinux:
    state: disabled
  become: true
