- name: Deploy openstack using kolla-ansible
  hosts: deployment_host
  remote_user: centos
  vars:
    local_registry: true
    docker_registry: 10.67.125.23:4000
    docker_namespace: aep-poc-latest
    kolla_internal_vip_address: 10.0.10.123
    network_interface: eth0
    network_external_interface: tap0
    ops_controls: "{{ groups['controller_host'] }}"
    ops_computes: "{{ groups['compute_host'] }}"
    ops_networks: "{{ groups['neutron_server_host'] }}"
    ops_storages: "{{ groups['compute_host'] }}"
    ops_monitors: "{{ groups['controller_host'] }}"
  roles:
    - ops-deploy
