- include: opsenv-pre.yaml

- name: Set up the environment/Preparation before openstack deployment with root user, for intel special part, on all the neutron server nodes
  hosts: neutron_server_host
  remote_user: centos
  become: true
  roles:
    - opsenv-net 

- include: ops-deploy.yaml

#- name: Up br-ex on neutron servers
#  hosts: neutron_server_host
#  remote_user: centos
#  become: true 
#  roles:
#    - exnet-enable 

- include: exnet-enable.yaml

# Defaults:
# os_image_path: "/tmp/centos.qcow2"
# os_name: centos
# os_type: linux
- name: Post deploy work for using openstack
  hosts: controller1_host
  vars:
    os_image_path: /home/centos/workspace/centos.qcow2
  vars_files:
    - roles/ops-deploy/vars/main.yaml
  remote_user: centos 
  roles:
    - post-deploy

# Defaults:
# os_name: centos
# vm_name: demovm
# pmem_vm_name: pmemvm
# vm_num: 2
# flavor_name: m1.small
- name: Create/Delete different VMs
  hosts: controller1_host
  remote_user: centos 
  vars_files:
    - roles/ops-deploy/vars/main.yaml
  roles:
    - vms-op
