---
- name: Copy {{ memtier_yaml_file }} to remote
  copy:
    src: "{{ memtier_yaml_file }}"
    dest: "{{ memtier_yaml_file_dest }}"
  run_once: true

- name: Modify amount of pods in {{ memtier_yaml_file_dest }}
  replace:
    path: "{{ memtier_yaml_file_dest }}"
    regexp: "{{ memtier_regexp }}"
    replace: "replicas: {{ memtier_pods }}"
    backup: yes
  run_once: true

- name: Create memtier pods
  block:
    - name: Run kubectl create -f {{ memtier_yaml_file_dest }}
      command: kubectl create -f {{ memtier_yaml_file_dest }}
      register: result

    - debug: msg="{{ result.stdout_lines }}"
      when: debug_mode | bool
  run_once: true
