---
- name: Get the total number of op/s
  block:
    - name: Run getops.py to get result
      shell: '{{ pythonbin }} getops.py {{ local_temp }}/result-aof-{{ memtier_pods }}-{{ memtier_iter_no }} {{ memtier_pods }}'
      args:
        chdir: "{{ role_path }}/files"
      register: result

    - debug: msg="{{ result.stdout_lines }}"
      when: debug_mode | bool
  delegate_to: "{{ k8s_master_ip }}"
  run_once: true
