---
## Update $HOME/.kube under non-root environment
## Let current user use kubectl
- name: Remove existing $HOME/.kube
  file:
    path: "{{ local_home }}/.kube"
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ kubespray_inventory_master_hosts }}"

- name: Create new $HOME/.kube
  file:
    path: "{{ local_home }}/.kube"
    state: directory
  delegate_to: "{{ item }}"
  loop: "{{ kubespray_inventory_master_hosts }}"

- name: Copy admin.conf to $HOME/.kube
  shell: cp /etc/kubernetes/admin.conf "{{ local_home }}/.kube/config"
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ kubespray_inventory_master_hosts }}"

- name: Change user and group permissions
  file:
    path: "{{ local_home }}/.kube/config"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0644"
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ kubespray_inventory_master_hosts }}"
