---
- name: Get local variables of kubespray inventory
  include_vars:
    file: "{{ kubespray_path }}/inventory/mycluster/hosts.yaml"
    name: host_vars

- name: Get one of kube-master's hostname from kubespray inventroy file
  set_fact:
    k8s_master_node: "{{ host_vars.all.children['kube-node'].hosts.keys()[0] }}"

- debug: msg="{{ k8s_master_node }}"
  when: debug_mode | bool

- name: Get kube-master's IP from kubespray inventroy file
  set_fact:
    k8s_master_ip: "{{ item.value.ip }}"
  when:
    - item.key == k8s_master_node
  with_dict: "{{ host_vars.all.hosts }}"

- debug: msg="{{ k8s_master_ip }}"
  when: debug_mode | bool

## Update $HOME/.kube under non-root environment
- name: Let current user use kubectl
  block:
    - name: Remove existing $HOME/.kube
      file:
        path: "{{ local_home }}/.kube"
        state: absent

    - name: Create new $HOME/.kube
      file:
        path: "{{ local_home }}/.kube"
        state: directory

    - name: Copy admin.conf to $HOME/.kube
      shell: cp /etc/kubernetes/admin.conf "{{ local_home }}/.kube/config"
      become: true

    - name: Change user and group permissions
      file:
        path: "{{ local_home }}/.kube/config"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: "0644"
      become: true
  delegate_to: "{{ k8s_master_ip }}"
  run_once: true
