---
- name: Show pods in all namespace
  command: kubectl get pods --all-namespaces
  register: result
  delegate_to: "{{ kubespray_inventory_master_hosts[0] }}"
  run_once: true

- debug: msg="{{ result }}"
  when: debug_mode | bool
