#- name: Dispatch the keyrings to the appropriate servers
#  block:
#    - copy:
#        src: "{{ keyringcache }}/client.{{ item.name }}.keyring"
#        dest: "{{ keyringdest }}/client.{{ item.name }}.keyring"
#    - file:
#        path: "{{ keyringdir }}/client.{{ item.name }}.keyring"
#        owner: "{{ item.owner }}"
#        group: "{{ item.owner }}"
#      when: "{{ item.chown }} != {{ false }}"
# # resused or included from externel task
# with_items:
#   - { name: glance, owner: glance , chown: true }
#   - { name: cinder, owner: cinder , chown: true }
#   - { name: cinder-backup, owner: cinder, chown: true }
#   - { name: cinder, owner: cinder , chown: false }  
#  tags: ceph_keyring_dph

- name: Copy the ceph.conf and keyrings to the appropriate config
  block:
    - name: Create {{ kollaconfig }}/{{ item.dest }}
      file:
        path: "{{ kollaconfig }}/{{ item.dest }}"
        state: directory

    - name: Copy ceph.conf to {{ kollaconfig }}/{{ item.dest }}
      copy:
        src: "{{ cephconfig }}/ceph.conf"
        dest: "{{ kollaconfig }}/{{ item.dest }}/ceph.conf"

    - name: Copy keyring to {{ kollaconfig }}/{{ item.dest }}
      copy:
        src:  "{{ cephconfig }}/ceph.client.{{ item.name }}.keyring"
        dest: "{{ kollaconfig }}/{{ item.dest }}/ceph.client.{{ item.rename }}.keyring"
# with_items:
#   - { name: glance,        rename: glance,        dest: glance }
#   - { name: cinder,        rename: cinder,        dest: cinder/cinder-volume }
#   - { name: cinder,        rename: cinder,        dest: cinder/cinder-backup }
#   - { name: cinder-backup, rename: cinder-backup, dest: cinder/cinder-backup }
#   - { name: cinder,        rename: nova,          dest: nova }     
