## Create secret key and add it to libvirt
- name: Create secret key with a new uuid
  block:
    # Generate new uuid
    - command: uuidgen
      register: result

    - set_fact:
        secret_uuid: "{{ result.stdout }}" # here it's not result.stdout_lines

    - debug: msg="new uuid {{ secret_uuid }}"
      when: debug_mode | bool      

    - copy:
        src: secret.xml.sample
        dest: "{{ secret_temp }}"
    
    - replace:
        path: "{{ item }}"
        regexp: "###INSERT_UUID###"
        replace: "{{ secret_uuid }}"
      with_items:
        - "{{ secret_temp }}"
        - "{{ kollaconfig }}/cinder/cinder-volume.conf"
        - "{{ kollaconfig }}/nova/nova-compute.conf"
    # Save the uuid to a temporary file
    - local_action: copy content="{{ secret_uuid }}" dest="{{ uuid_backup }}"
