- name: Show ceph status
  command: ceph status
  register: result
  become: true
  delegate_to: "{{ ceph_host }}"
    
- debug: msg="{{ result.stdout_lines }}"  
  when: debug_mode | bool

- name: List created pools
  command: ceph osd pool ls
  register: result
  become: true
  delegate_to: "{{ ceph_host }}"

- debug: msg={{ result.stdout_lines }}
  when: debug_mode | bool
