- name: Fill {{ objconf.section }} section in ini
  ini_file:
    path: "{{ objconf.ini }}"
    section: "{{ objconf.section }}"
    option: "{{ item }}"
    allow_no_value: true
    state: present
  with_items: "{{ objconf.options }}"
