# Optional

# Configure network proxy on all the nodes
- block:
    - name: Generate network proxy variables
      template:
        src: global_proxy.j2
        dest: "{{ local_temp }}/netproxy"

    - name: Append network proxy variables in global profile
      blockinfile:
        path:  /etc/profile
        block: "{{ lookup('file', '{{ local_temp }}/netproxy') }}"

    - name: Export network proxy variables
      shell: source /etc/profile
  when: global_proxy | bool

# Configure docker proxy on all the nodes
# kolla-ansible/contrib/dev/vagrant/bootstrap.sh:118 do same
- block:
    - name: Generate docker proxy
      template:
        src: docker_proxy.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    
    - name: Reload docker services
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
  when: docker_proxy | bool

# Configure yum proxy on deployment node
- name: Set yum proxy
  ini_file:
    path: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ http_proxy }}"
  when: global_proxy | bool
