- name: Install tools and utility packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - wget
    - curl
    - unzip
    - git
    - gcc
    - net-tools
    - python-pip
