- block:
    - name: Ensure yum repos directory exists
      file:
        path: /etc/yum.repos.d/
        state: directory
        recurse: yes
      become: True

    - name: Enable docker yum repository
      yum_repository:
        name: docker
        description: Docker main Repository
        baseurl: "{{ docker_yum_baseurl }}"
        gpgcheck: "{{ docker_yum_gpgcheck | bool }}"
        gpgkey: "{{ docker_yum_gpgkey }}"
      become: True

    - name: Install docker rpm gpg key
      rpm_key:
        state: present
        key: "{{ docker_yum_url }}/gpg"
      become: True
      when: docker_yum_gpgcheck | bool
  when: enable_docker_repo | bool and docker_exist.rc == 1

- name: Install RPM packages
  package:
    name: "{{ (redhat_pkg_install | join(' ')).split() }}"
    state: present
    update_cache: yes
  become: True

- name: Make docker available without sudo
  block:
    - name: Add 'docker' group
      group:
        name: docker
        state: present

    - name: Add ansible_user to 'docker' group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: True

    - name: Restart docker service
      systemd:
        name: docker.service
        state: restarted
      become: True
  when: enable_docker_repo | bool

- name: Reset ssh connection to make affect
  meta: reset_connection
