# Docker Yum repository configuration.
docker_yum_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
docker_yum_baseurl: "{{ docker_yum_url }}/7/$basearch/stable"
docker_yum_gpgkey: "{{ docker_yum_url }}/gpg"
docker_yum_gpgcheck: true
docker_yum_package: "docker-ce"

redhat_pkg_install:
 - "{{ docker_yum_package }}"
